services:
    bubmask:
        stdin_open: true
        tty: true
        devices:
            - /dev/dri
        volumes:
            - ..:/root/BubMask
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        environment:
            - QT_X11_NO_MITSHM=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        container_name: bubmask-container
        build: .
        image: frakw/bubmask:latest
        command: /bin/bash
