services:
    ifa:
        stdin_open: true
        tty: true
        devices:
            - /dev/dri
        volumes:
            - .:/root/IFA
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        environment:
            - QT_X11_NO_MITSHM=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        ports:
            - "9090:8080"
        container_name: ifa-container
        build: .
        image: frakw/ifa:latest
        command: /bin/bash
        shm_size: 8G
        ipc: host
