services:
    finetune-sam:
        stdin_open: true
        tty: true
        devices:
            - /dev/dri
        volumes:
            - .:/root/finetune-SAM
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        environment:
            - QT_X11_NO_MITSHM=1
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        container_name: finetune-sam-container
        build: .
        image: frakw/finetune-sam:latest
        command: /bin/bash
        shm_size: 16G
        ipc: host
